---
# Setup centos 7 by adding all dependencies for this role
- name: Install some package 
  package: name='{{ item }}' state=present
  when: ansible_distribution == "CentOS"
  with_items:
    - epel-release
    - wget
    - git
- name: install python-pip
  yum: name=python-pip state=present update_cache=yes
- name: Install docker python
  pip: name=docker-py