---
- name: Authorize the necessary ports permanently for RedHat distro
  firewalld:
    port: "{{ item }}/tcp"
    permanent: yes
    immediate: yes
    state: enabled
  loop: "{{ kubernetes_control_plane_ports }}"
  when: ansible_os_family == "RedHat"

- name: Authorize the necessary ports permanently for Debian distro
  ufw:
    rule: allow
    port: "{{ item | regex_replace('-', ':') }}"
    proto: tcp
    state: reloaded
  loop: "{{ kubernetes_control_plane_ports }}"
  when: ansible_os_family == "Debian"

- import_tasks: init-control-plane-setup.yml
  when: kubernetes_role == 'primary_control_plane'

- import_tasks: join-control-plane-setup.yml
  when: kubernetes_role == 'secondary_control_plane'